name: "Bug Report"
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: project
      description: project 
      placeholder: ex. email@example.com
    validations:
      required: false
    
  
- type: input
    id: contact
    attributes:
      label: v1
      description: Commit for Version 1
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: v2
      description: Commit for Version 2
      placeholder: ex. email@example.com
    validations:
      required: false

