name: "Bug Report"
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: PJ
    attributes:
      label: project
      description: project 
      placeholder: ex. https://github.com/Divergence-Driven-Debugging/Echo
    validations:
      required: false
    
  
  - type: input
    id: cm1
    attributes:
      label: v1
      description: Commit for Version 1
      placeholder: ex. https://github.com/Divergence-Driven-Debugging/Echo/commit/cd50068d2870e5dce92d38f0e06c7879ac82aa28
    validations:
      required: false

  - type: input
    id: cm2
    attributes:
      label: v2
      description: Commit for Version 2
      placeholder: ex. https://github.com/Divergence-Driven-Debugging/Echo/commit/cd50068d2870e5dce92d38f0e06c7879ac82aa28
    validations:
      required: false

  - type: textarea
    id: scenario
    attributes:
      label: scenario
      description: Scenario to Execute in Both Versions
      placeholder: Transcript open
      render: shell
    validations:
      required: false
  

  

    
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 
    validations:
      required: false

  - type: textarea
    id: remarks
    attributes:
      label: remarks
      description: Additional Remarks
      placeholder: Include any supplementary observations, such as insights into the cause of the bug or its potential impact
      value: 
    validations:
      required: false



    
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: What os are you seeing the problem on?
      multiple: true
      options:
        - Mac
        - Windows
        - Other

  - type: textarea
    id: versioningPharo
    attributes:
      label: version
      description: Pharo version
      value: Pharo 12 / Moose 12 / ect
    validations:
      required: false


  - type: textarea
    id: versioningVm
    attributes:
      label: versionVM
      description: Pharo vm version
      placeholder: If you know the Pharo VM version
      value: Pharo 12 / Moose 12 / ect
    validations:
      required: false

